### ISSUE TITLE
Merge di modifiche fatte da ODN

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-odn#5]
- [ ] Modifiche grafiche alla pagina about_text con inclusione del logo e delle info sul Comune di Prato. 
- [ ] Modifca per visualizzare tutte e 13 le categorie nella home page

**Comment by etj** [comment]
Fixed by https://github.com/geosolutions-it/ckanext-odn/commit/1db9de45545389d494d1fa642283effb668db0ce
