### ISSUE TITLE
GeoName URI import

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-odn#6]
Harvester CSW: importare URI di GeoNames costante per tutti i dataset importati.

**Comment by etj** [comment]
Inserire nella configurazione dell'harvester il `default_extras` con chiave `geographical_geonames_url`.
Tutti i dataset importati da quell'harvester avranno la URI GeoNames impostata sul valore dato.

Es.:
```
{"default_extras":
   {
      "geographical_geonames_url": 
         "http://www.geonames.org/maps/google_46.5_11.333.html"
   }
}
```
